import Head from "next/head";

import Navbar from "../components/Navbar";
import Slider from "../components/Slider";
import Converter from "../components/Converter";
import Info from "../components/Info";
import NewsLetter from "../components/NewsLetter";
import Footer from "../components/Footer";
export default function Home() {
  return (
    <>
      <Head>
        <title>Shortly</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <Slider />
      <Converter />
      <Info />
      <NewsLetter />
      <Footer />
    </>
  );
}
